### ISSUE TITLE
Implement AGEPRO Recruitment Models 

### ISSUE THREAD

**Issue by efletcherPIFSC** [PIFSCstockassessments/ageproR#1]
Implement 20+ AGEPRO's Recruitment Models based on AGERPO Reference Manual and AGEPRO Core-Lib

- [X] 0. NULL (Default) 
- [ ] 1. Markov Matrix (#67)
- [x] 2. Empirical Per Spawning Biomass Distribution (SSB)
- [X] 3. Empirical 
- [x] 4.  Empirical Two-Stage Per SSB
- [x] 5. Beverton-Holt Curve w/ lognormal error 
- [x] 6. Ricker Curve w/ lognormal error
- [x] 7. Shepherd Curve w/ lognormal errors
- [ ] 8. Lognormal distribution
- [X] 9. **[DEPRECATED]** Time-Varying Empirical Recruitment Distribution
- [x] 10. Beverton-Holt curve w/ Autocorrelated lognormal error
- [x] 11. Ricker curve w/ Autocorrelated lognormal error
- [x] 12. Shepherd curve w/ Autocorrelated lognormal error 
- [ ] 13. Autocorrelated Lognormal Distribution
- [X] 14. Empirical CDF 
- [x] 15. Empirical CDF Two-Stage 
- [ ] 16. (Predictor) Linear Recruits Per SSB w/ Normal Error  (#66)
- [ ] 17. (Predictor) Loglinear Recruits Per SSB w/ Lognormal Error (#66)
- [ ] 18. (Predictor) Linear Recruitment w/ Normal Error (#66)
- [ ] 19. (Predictor) Loglinear Recruitment w/ Lognormal Error (#66)
- [ ] 20. Fixed 
- [ ] 21. Empirical CDF w/ Linear Decline to Zero
